### ISSUE TITLE
Outlier performance for long series and forecasting of seasonal component

### ISSUE THREAD

**Issue by jonlachmann** [timginker/boiwsa#3]
Hi!

I recently found this package and was happy to see that there is actually someone doing SA for weekly data. I was trying it out for some longer series (3000 obs). I found that the outlier adjustment function was rather slow, so I spent some time working on it and applied the Sherman-Morrison formula to update the inverse when evaluating the different potential outliers. It reduced computational complexity from np^2 to np which brought the time of adjusting 3000 obs to ~4 minutes compared to hours which it took on my first try.

Another thing that I noticed is that there is no option to produce a forecast of the seasonal component which is quite important when one wants to use the adjusted series for forecasting. I modified the code further to allow for this by just feeding more dates to the fourier_vars function and estimating the regression on historical data but creating the prediction based on the full sample plus user specified horizon.

Finally I also ran ```styler``` on the whole code to ensure that the code conforms to R coding guidelines. I also removed the inlined functions withing ```boiwsa``` and broke out some parts of it to avoid too much repetition and get an easier overview of the algorithm.

I was wondering if this is a set of changes that you would be interested in merging into the master branch? I would be happy to provide two separate PRs, one which styles and refactors the code and another which provides the subsequent feature/performance changes. I am thinking that this would make the review work easier as a composite PR would make it hard to see what is code style/refactoring and what are the new features and performance improvements.

Best,
Jon

**Comment by timginker** [comment]
Hi Jon,

Thank you! That sounds great. Regarding the forecast, I store the last
vector of coefficients (since it is a local regression) as beta in the
arguments. It can be used, combined with regressors, to predict the future
values of the seasonal component. However, to predict the overall level, it
needs to be combined with auto.arima fitted to the seasonally adjusted
series. This method would be similar to the forecast’s S3 method for STL.

I would be happy to review the changes and, if possible, discuss them with
you (maybe through Zoom). However, you caught me in a rather busy period.
We have holidays now, and I won’t be available for the next 10 days. So, it
will take me some time to go through the changes.

Best wishes,
Tim

‫בתאריך יום ה׳, 10 באוק׳ 2024 ב-8:46 מאת ‪jonlachmann‬‏ <‪
***@***.***‬‏>:‬

**Comment by timginker** [comment]
Many thanks to Jon for the improved outlier search performance!
